Improve file redirection to not use stdout
This ensures only the original command's output is directed to stdout.

diff --git a/awsh b/awsh
--- a/awsh
+++ b/awsh
@@ -36,7 +36,7 @@ done
 
 # If no host specified, offer a fuzzy selection
 if [ -z "${username_host}" ]; then
-  echo "No user@hostname specified, fetching available instances..."
+  echo "No user@hostname specified, fetching available instances..." >&2
   instances="$(aws ec2 describe-instances --filter Name=instance-state-name,Values=running --output json | jq -r '.Reservations[].Instances[] | .InstanceId + "\t" + .PrivateIpAddress + "\t" + (.Tags[]? | select(.Key == "Name") | .Value // "(No name tag)")')"
   ssh_host="$(echo "$instances" | sort -rk2 | fzf | cut -f2)"
   ssh_user="${SSH_USER:-ec2-user}"
@@ -64,16 +64,16 @@ ip_address="$(resolve-ip "$ssh_host")"
 instance_id="$(aws ec2 describe-instances --query "Reservations[*].Instances[?PrivateIpAddress == '${ip_address}' || PublicIpAddress == '${ip_address}'].InstanceId" --output text)"
 
 if [ -z "$instance_id" ]; then
-  echo "Unable to resolve $ssh_host to an AWS EC2 instance ID"
+  echo "Unable to resolve $ssh_host to an AWS EC2 instance ID" >&2
   exit 1
 fi
 
-echo "Generating a temporary SSH key..."
+echo "Generating one-time-use SSH key..." >&2
 tmp_key_file="$(mktemp)"
 ssh-keygen -t ed25519 -f "$tmp_key_file" -C "" -P "" -q <<<y >/dev/null 2>&1
 pub_key="$(cat "${tmp_key_file}.pub")"
 
-echo "Adding temporary SSH key to instance ID $instance_id (IP $ip_address)..."
+echo "Adding temporary SSH key to instance ID $instance_id (IP $ip_address)..." >&2
 aws ec2-instance-connect send-ssh-public-key \
   --instance-id "$instance_id" \
   --instance-os-user "$ssh_user" \
@@ -84,13 +84,13 @@ aws ec2-instance-connect send-ssh-public-key \
 flags+=("-oStrictHostKeyChecking=no")
 flags+=("-oUserKnownHostsFile=/dev/null")
 
-echo "Connecting to instance ID $instance_id (IP $ip_address)..."
+echo "Connecting to instance ID $instance_id (IP $ip_address)..." >&2
 if [ ${#command_args[@]} -gt 0 ]; then
-  exec ssh -i "$tmp_key_file" \
+  ssh -i "$tmp_key_file" \
     "-oProxyCommand=aws ec2-instance-connect open-tunnel --instance-id $instance_id" \
     "${flags[@]}" "$ssh_user@$instance_id.ec2.internal" "${command_args[@]}"
 else
-  exec ssh -i "$tmp_key_file" \
+  ssh -i "$tmp_key_file" \
     "-oProxyCommand=aws ec2-instance-connect open-tunnel --instance-id $instance_id" \
     "${flags[@]}" "$ssh_user@$instance_id.ec2.internal"
 fi
